num1=print("Introduce el primer numero: ")
num1=int(input())
num2=print("Introduce el segundo numero: ")
num2=int(input())
print("La suma es: ", num1+num2)
print("La resta es: ", num1-num2)
print("La multiplicacion es: ", num1*num2)
print("La division es: ", num1/num2)